# Generated by Django 5.0.3 on 2024-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('Ok', 'Ok'), ('Decline', 'Decline')], db_index=True, max_length=100)),
                ('departments', models.CharField(choices=[('emergency', 'Emergency Department'), ('internal_medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('obstetrics_gynecology', 'Obstetrics and Gynecology'), ('pediatrics', 'Pediatrics'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology'), ('intensive_care', 'Intensive Care Unit (ICU)'), ('oncology', 'Oncology'), ('psychiatry', 'Psychiatry'), ('physical_therapy', 'Physical Therapy and Rehabilitation'), ('pharmacy', 'Pharmacy')], db_index=True, max_length=200)),
                ('phone_no', models.IntegerField(db_index=True)),
                ('scheduled_day', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bed_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('reservation_date', models.DateField(db_index=True)),
                ('de_reservation_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('Reserve', 'Reserve'), ('Available', 'Available')], db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_no', models.IntegerField(db_index=True)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField(db_index=True)),
                ('status', models.CharField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved')], db_index=True, max_length=100)),
                ('contact_ticket', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('reservation', 'Reservation'), ('appointment_booking', 'Appointment Booking'), ('admin_notification', 'Admin Notification')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(db_index=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
