# Generated by Django 5.0.3 on 2024-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='bed_reservation',
            name='status',
            field=models.CharField(choices=[('Reserve', 'Reserve'), ('Pending', 'Pending'), ('Available', 'Available'), ('Decline', 'Decline')], db_index=True, max_length=100),
        ),
    ]
