# Generated by Django 5.0.3 on 2024-04-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_appointment_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
