# Generated by Django 5.0.3 on 2024-03-30 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Admin', 'Admin')], db_index=True, max_length=100, null=True)),
                ('username', models.CharField(db_index=True, max_length=100, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('bio', models.TextField(null=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not confirmed', 'Not confirmed')], db_index=True, max_length=100, null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('otp', models.PositiveIntegerField(null=True)),
                ('otp_limit', models.IntegerField(null=True)),
                ('otp_delay', models.TimeField(auto_now=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('doctor_cv', models.FileField(db_index=True, null=True, upload_to='')),
                ('speciality', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('hematology', 'Hematology'), ('neurology', 'Neurology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('otolaryngology', 'Otolaryngology (ENT)'), ('pediatrics', 'Pediatrics'), ('pulmonology', 'Pulmonology'), ('urology', 'Urology')], db_index=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=50, null=True)),
                ('years_of_experience', models.PositiveIntegerField(null=True)),
                ('education_background', models.TextField(null=True)),
                ('certifications', models.TextField(null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
