# Generated by Django 5.0.3 on 2024-04-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='user',
            name='exceed_quota',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(null=True),
        ),
    ]
