# Generated by Django 5.0.3 on 2024-04-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0002_remove_user_years_of_experience_user_exceed_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exceed_quota',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
