# Generated by Django 5.0.3 on 2024-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0003_alter_user_exceed_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_toggler',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('ophthalmology', 'Ophthalmology')], db_index=True, max_length=100, null=True),
        ),
    ]
